//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Furniture_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public int id_product { get; set; }
        public string product_name { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> amount { get; set; }
        public string color { get; set; }
        public string product_description { get; set; }
        public string photo_1 { get; set; }
        public string photo_2 { get; set; }
        public string photo_3 { get; set; }
    }
}
