//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Furniture_Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_
    {
        public int id_user { get; set; }
        public string user_login { get; set; }
        public string user_password { get; set; }
        public string user_name { get; set; }
        public string user_surname { get; set; }
        public string user_patronomic { get; set; }
        public string user_adress { get; set; }
    }
}
